spring.application.name=api-gateway
server.port=8080

spring.data.redis.ssl.enabled=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

json.service.url=${JSON_SERVICE_URL:http://localhost:8084}
soap.service.url=${SOAP_URL:http://localhost:9002/auth}
file.service.url=${FILE_SERVICE_URL:http://localhost:8085}spring.application.name=api-gateway
server.port=8080

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

json.service.url=${JSON_SERVICE_URL:http://localhost:8084}
soap.service.url=${SOAP_URL:http://localhost:9002/auth}
file.service.url=${FILE_SERVICE_URL:http://localhost:8085}